instagram.client.id: 258521991996038
instagram.secret.id: 2c2c055a88290d04b1fb85b6502407f1
instagram.accesstoken.endpoint: https://api.instagram.com/oauth/access_token/
instagram.redirect.auth.link: https://localhost:3000/
instagram.userdata.endpoint: https://graph.instagram.com/me/
instagram.usermedia.endpoint: https://graph.instagram.com/me/media/
facebook.graph.client.id: 156680885641647
facebook.graph.secret.id: f770f942a988bacdc828b4abb6a9607b
facebook.graph.endpoint: https://graph.facebook.com
facebook.graph.longlife.token.endpoint: https://graph.facebook.com/oauth/access_token
facebook.graph.user.endpoint: https://graph.facebook.com/me
facebook.graph.accounts.pathparams: /me/accounts?access_token=
facebook.graph.IGaccount.pathparams: ?fields=instagram_business_account&access_token=
facebook.graph.insights.day.pathparams: /insights?metric=reach,impressions,email_contacts,follower_count,get_directions_clicks,phone_call_clicks,profile_views,text_message_clicks,website_clicks&period=day&access_token=
facebook.graph.insights.lifetime.pathparams: /insights?metric=audience_city,audience_country,audience_gender_age,audience_locale&period=lifetime&access_token=
facebook.graph.media.pathparams: /media?fields=caption,thumbnail_url,like_count,comments_count,comments,media_type,media_url,timestamp&access_token=
facebook.graph.stories.pathparams: /stories?fields=caption,thumbnail_url,like_count,comments_count,comments,media_type,media_url,timestamp&access_token=
facebook.graph.image.media.insight.pathparams: /insights?metric=reach,impressions,engagement,saved&access_token=
facebook.graph.video.media.insight.pathparams: /insights?metric=reach,impressions,engagement,saved,video_views&access_token=
facebook.graph.album.media.insight.pathparams: /insights?metric=carousel_album_engagement,carousel_album_impressions,carousel_album_reach,carousel_album_saved&access_token=
facebook.graph.story.media.insight.pathparams: /insights?metric=reach,impressions,exits,replies,taps_forward,taps_back&access_token=
facebook.graph.ig.account.details: ?fields=follows_count,followers_count,profile_picture_url,name,username,media_count&access_token=



spring:
    datasource:
        url: jdbc:mysql://localhost:3306/spring_social?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: toor

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
              clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 121189305185277
              clientSecret: 42ffe5aa7379e8326387e0fe16f34132
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - public_profile
            github:
              clientId: d3e47fc2ddd966fa4352
              clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

